version: '3.8'
services:
  nexus:
    image: 'sonatype/nexus3:3.29.2'
    restart: always
    ports:
      - '8080:80'
      - '8081:8081'
      - '443:443'
    volumes:
      - './nexus-data:/nexus-data'

